### ISSUE TITLE
1- best practice for directory structure

### ISSUE THREAD

**Issue by artmarydotir** [m-kh-paladin/js_tasks#1]
- **src** folder is where you put the code base.
- its better not to put  _package-lock.json_, _package.json_  , _.eslintrc.js_ , .... in it.

**Comment by m-kh-paladin** [comment]
sry i just misunderstood , i imaged i have to call my own folder to SRC - i fixed it - but i just puts my tasks files in it if its wrong so just tell me to fix it again

**Comment by m-kh-paladin** [comment]
> * **src** folder is where you put the code base.
> 
>     * its better not to put  _package-lock.json_, _package.json_  , _.eslintrc.js_ , .... in it.


sry i just misunderstood , i imaged i have to call my own folder to SRC - i fixed it - but i just puts my tasks files in it if its wrong so just tell me to fix it again
