### ISSUE TITLE
2- where is the prettier package ?

### ISSUE THREAD

**Issue by artmarydotir** [m-kh-paladin/js_tasks#2]
![Screenshot from 2023-07-09 11-46-27](https://github.com/m-kh-paladin/js_tasks/assets/11363931/448aad43-e703-4d73-81fd-1ba0d95105fc)

you have to install prettier package too. and config it in .**prettierrc** .
you just install eslint.

**Comment by m-kh-paladin** [comment]
> ![Screenshot from 2023-07-09 11-46-27](https://user-images.githubusercontent.com/11363931/252133859-448aad43-e703-4d73-81fd-1ba0d95105fc.png)
> 
> you have to install prettier package too. and config it in .**prettierrc** . you just install eslint.

on that time cuz i several times deleted all off my file for try at first point i think for last time u forgot to install this package again - sry - i fix it
