### ISSUE TITLE
3- mistake in .eslintrc.js file

### ISSUE THREAD

**Issue by artmarydotir** [m-kh-paladin/js_tasks#3]
you extend prettier in  eslintrc config file, but you never add it in package-json.
![Screenshot from 2023-07-09 11-54-01](https://github.com/m-kh-paladin/js_tasks/assets/11363931/cffc3a73-edb9-4c11-9646-0573f22cf73f)

**WARN**: you should **not** add any plugin in your config file, unless you install its dependency.

**Comment by m-kh-paladin** [comment]
> you extend prettier in eslintrc config file, but you never add it in package-json. ![Screenshot from 2023-07-09 11-54-01](https://user-images.githubusercontent.com/11363931/252134143-cffc3a73-edb9-4c11-9646-0573f22cf73f.png)
> 
> **WARN**: you should **not** add any plugin in your config file, unless you install its dependency.

u are right - i fix it again
