### ISSUE TITLE
4- where is the eslint script?

### ISSUE THREAD

**Issue by artmarydotir** [m-kh-paladin/js_tasks#4]
when we use a tools like **eslint** or **prettier**, there must be a task or script that we can run on our code , therefore to see the result.

how can i run eslint?
- think about it.
- see the videos i sent before.
- implement this part again.

**Comment by m-kh-paladin** [comment]
> when we use a tools like **eslint** or **prettier**, there must be a task or script that we can run on our code , therefore to see the result.
> 
> how can i run eslint?
> 
>     * think about it.
> 
>     * see the videos i sent before.
> 
>     * implement this part again.

If I want to be honest on that time for my limited time i just tried to copy these files but this time i just do some research and now its completely
